export const MaoCouponType=[
    {
      id:0,
      value:300,
      Csort:'全部',
      assignItemId:null,
      rule:'一律',
      slogan:'全館商品現折300',
      payLevel:0,
      amount:1},
    {
      id:1,
      value:0.8,
      Csort:'耳機/喇叭',
      assignItemId:null,
      rule:'滿額打折',
      slogan:'滿2000 耳機/喇叭分類 8折',
      payLevel:2000,
      amount:1},
    {
      id:2,
      value:200,
      Csort:'運動攝影機',
      assignItemId:[153,151],
      rule:'滿額折現',
      slogan:'指定商品滿五千現折200',
      payLevel:5000,
      amount:1},
    {
      id:3,
      value:0.5,
      Csort:'運動攝影機',
      assignItemId:null,
      rule:'滿件打折',
      slogan:'滿兩件五折',
      payLevel:0,
      amount:2}
  ]