export const MaoCouponType=[
    {
      id:0,
      value:3000,
      Csort:'全部',
      Cname:null,
      rule:'一律',
      slogan:'全部商品-結帳金額折扣3000',
      payLevel:0,
      amount:1},
    {
      id:1,
      value:0.8,
      Csort:'穿戴式裝置',
      Cname:'GARMIN',
      rule:'滿額打折',
      slogan:'穿戴式裝置分類-滿15000打8折',
      payLevel:15000,
      amount:1},
    {
      id:2,
      value:2000,
      Csort:'運動攝影機',
      Cname:'GoPro',
      rule:'滿額折現',
      slogan:'運動攝影機分類-滿10000折扣2000',
      payLevel:10000,
      amount:1},
    {
      id:3,
      value:0.8,
      Csort:'耳機/喇叭',
      Cname:'SONY',
      rule:'滿件打折',
      slogan:'耳機/喇叭分類-滿2件打8折',
      payLevel:0,
      amount:2}
  ]