export const MaoCouponType=[
    {
      id:0,
      value:300,
      Csort:'全部',
      assignItemId:null,
      rule:'一律',
      slogan:'全館商品現折3000',
      payLevel:0,
      amount:1},
    {
      id:1,
      value:0.8,
      Csort:'耳機/喇叭',
      assignItemId:null,
      rule:'滿額打折',
      slogan:'滿15000 耳機/喇叭分類 8折',
      payLevel:15000,
      amount:1},
    {
      id:2,
      value:2000,
      Csort:'運動攝影機',
      assignItemId:[153,151],
      rule:'滿額折現',
      slogan:'指定商品滿一萬現折2000',
      payLevel:10000,
      amount:1},
    {
      id:3,
      value:0.8,
      Csort:'運動攝影機',
      assignItemId:null,
      rule:'滿件打折',
      slogan:'滿兩件8折',
      payLevel:0,
      amount:2}
  ]