export const productList = [
  {
    id: 1,
    pId: 'p001',
    pName: 'Apple Watch Nike1',
    price: 100,
    itemCategoryId: '周邊',
    name: 'Apple8',
  },
  {
    id: 2,
    pId: 'p002',
    pName: 'Apple Watch Nike2',
    price: 200,
    itemCategoryId: '周邊',
    name: 'Apple9',
  },
  {
    id: 3,
    pId: 'p003',
    pName: 'Apple Watch Nike3',
    price: 300,
    itemCategoryId: '周邊',
    name: 'Apple2',
  },
  {
    id: 4,
    pId: 'p004',
    pName: 'Apple Watch Nike4',
    price: 400,
    itemCategoryId: '穿戴式裝置',
    name: 'Apple3',
  },
  {
    id: 5,
    pId: 'p005',
    pName: 'Apple Watch Nike5',
    price: 500,
    itemCategoryId: '穿戴式裝置',
    name: 'Apple4',
  },
  {
    id: 6,
    pId: 'p006',
    pName: 'Apple Watch Nike6',
    price: 600,
    itemCategoryId: '穿戴式裝置',
    name: 'Apple4',
  },
  {
    id: 7,
    pId: 'p007',
    pName: 'Apple Watch Nike6',
    price: 700,
    itemCategoryId: '穿戴式裝置',
    name: 'Apple8',
  },
  {
    id: 8,
    pId: 'p008',
    pName: 'Apple Watch Nike6',
    price: 800,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple1',
  },
  {
    id: 9,
    pId: 'p009',
    pName: 'Apple Watch Nike6',
    price: 900,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple3',
  },
  {
    id: 10,
    pId: 'p010',
    pName: 'Apple Watch Nike6',
    price: 1000,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple7',
  },
  {
    id: 11,
    pId: 'p011',
    pName: 'Apple Watch Nike6',
    price: 1100,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple6',
  },
  {
    id: 12,
    pId: 'p012',
    pName: 'Apple Watch Nike6',
    price: 1200,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple1',
  },
  {
    id: 13,
    pId: 'p013',
    pName: 'Apple Watch Nike6',
    price: 1300,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple2',
  },
  {
    id: 14,
    pId: 'p014',
    pName: 'Apple Watch Nike6',
    price: 1400,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple3',
  },
  {
    id: 15,
    pId: 'p015',
    pName: 'Apple Watch Nike6',
    price: 1500,
    itemCategoryId: '運動攝影機',
    name: 'Apple5',
  },
  {
    id: 16,
    pId: 'p016',
    pName: 'Apple Watch Nike6',
    price: 1600,
    itemCategoryId: '運動攝影機',
    name: 'Apple',
  },
  {
    id: 17,
    pId: 'p017',
    pName: 'Apple Watch Nike6',
    price: 1700,
    itemCategoryId: '周邊',
    name: 'Apple6',
  },
  {
    id: 18,
    pId: 'p018',
    pName: 'Apple Watch Nike6',
    price: 1800,
    itemCategoryId: '運動攝影機',
    name: 'Apple8',
  },
  {
    id: 19,
    pId: 'p019',
    pName: 'Apple Watch Nike6',
    price: 1900,
    itemCategoryId: '運動攝影機',
    name: 'Apple6',
  },
  {
    id: 20,
    pId: 'p020',
    pName: 'Apple Watch Nike6',
    price: 2000,
    itemCategoryId: '耳機/喇叭',
    name: 'Apple5',
  },
  {
    id: 21,
    pId: 'p021',
    pName: 'Apple Watch Nike6',
    price: 2100,
    itemCategoryId: '運動攝影機',
    name: 'Apple10',
  },
  {
    id: 22,
    pId: 'p022',
    pName: 'Apple Watch Nike6',
    price: 2200,
    itemCategoryId: '運動攝影機',
    name: 'Apple10',
  },
]
