
  export const productList = [
    {
      id: 1,
      pId: 'p001',
      pName: 'Apple Watch Nike1',
      price: 100,
    },
    {
      id: 2,
      pId: 'p002',
      pName: 'Apple Watch Nike2',
      price: 200,
    },
    {
      id: 3,
      pId: 'p003',
      pName: 'Apple Watch Nike3',
      price: 300,
    },
    {
      id: 4,
      pId: 'p004',
      pName: 'Apple Watch Nike4',
      price: 400,
    },
    {
      id: 5,
      pId: 'p005',
      pName: 'Apple Watch Nike5',
      price: 500,
    },
    {
      id: 6,
      pId: 'p006',
      pName: 'Apple Watch Nike6',
      price: 600,
    },
    {
      id: 7,
      pId: 'p007',
      pName: 'Apple Watch Nike6',
      price: 700,
    },
    {
      id: 8,
      pId: 'p008',
      pName: 'Apple Watch Nike6',
      price: 800,
    },
    {
      id: 9,
      pId: 'p009',
      pName: 'Apple Watch Nike6',
      price: 900,
    },
    {
      id: 10,
      pId: 'p010',
      pName: 'Apple Watch Nike6',
      price: 1000,
    },
    {
      id:11,
      pId: 'p011',
      pName: 'Apple Watch Nike6',
      price: 1100,
    },
    {
      id: 12,
      pId: 'p012',
      pName: 'Apple Watch Nike6',
      price: 1200,
    },
    {
      id: 13,
      pId: 'p013',
      pName: 'Apple Watch Nike6',
      price: 1300,
    },
    {
      id: 14,
      pId: 'p014',
      pName: 'Apple Watch Nike6',
      price: 1400,
    },
    {
      id: 15,
      pId: 'p015',
      pName: 'Apple Watch Nike6',
      price: 1500,
    },
    {
      id: 16,
      pId: 'p016',
      pName: 'Apple Watch Nike6',
      price: 1600,
    },
    {
      id: 17,
      pId: 'p017',
      pName: 'Apple Watch Nike6',
      price: 1700,
    },
    {
      id: 18,
      pId: 'p018',
      pName: 'Apple Watch Nike6',
      price: 1800,
    },
    {
      id: 19,
      pId: 'p019',
      pName: 'Apple Watch Nike6',
      price: 1900,
    },
    {
      id: 20,
      pId: 'p020',
      pName: 'Apple Watch Nike6',
      price: 2000,
    },
    {
      id: 21,
      pId: 'p021',
      pName: 'Apple Watch Nike6',
      price: 2100,
    },
    {
      id: 22,
      pId: 'p022',
      pName: 'Apple Watch Nike6',
      price: 2200,
    },
  ]

